version: '2'

services:

  # Consul
  consul:
    image: consul:0.7.5
    command: "agent -dev -client 0.0.0.0 -ui"
    container_name: consul
    ports:
      - 8301
      - 8500:8500
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - SERVICE_IGNORE=true

  # Registrator
  registrator:
    image: nhuray/registrator:v7
    command: "-internal consul://consul:8500"
    container_name: registrator
    depends_on:
      - consul
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock

  # Cloudwatch exporter
  cloudwatch-exporter:
    build:
      context: .
      dockerfile: versions/latest/Dockerfile
    command: "java -jar /cloudwatch_exporter.jar 9106 /config/config.yml"
    depends_on:
      - consul
    ports:
      - 9106:9106
    environment:
      - SERVICE_TAGS=metrics
      - SERVICE_NAME=cloudwatch-exporter
      - CONSUL_HTTP_ADDR=consul:8500

  # Consulator
  consulator:
    image: lewispeckover/consulator
    command: "sync -prefix=service /app/consulator.yml"
    container_name: consulator
    depends_on:
      - consul
    volumes:
      - ./consulator.yml:/app/consulator.yml
    environment:
      - CONSUL_HTTP_ADDR=consul:8500