#!/usr/bin/env bats
load helpers

# Declare the service
consul_service="consul"
address="$(dig +short ${consul_service})"
port="8500"
service="statsd-exporter"

@test "Check '/etc/statsd_exporter/statsd_exporter.config' configuration is well rendered" {

  value="content"
  template="/etc/consul-template/templates/statsd_exporter.ctmpl"
  file="/etc/statsd_exporter/statsd_exporter.config"

  # Remove the default configuration
  status=$(rm -f ${file};echo $?)
  [ "$status" -eq 0 ]

  # Register the file
  run register_key "service/${service}/statsd_exporter.config" "${value}"
  [ "$status" -eq 0 ]

  # Call consul template to generate the configuration
  status=$(consul-template -consul-addr ${consul_service}:8500 -template ${template}:${file} -once;echo $?)
  [ "$status" -eq 0 ]

  # Check the expected configuration has been generated by consul-template
  status=$(test -f ${file};echo $?)
  [ "$status" -eq 0 ]

  # Check we can find the content
  status=$(grep "${value}" ${file} 2>&1 > /dev/null;echo $?)
  [ "$status" -eq 0 ]

}